/**
 * FLAME 框架数据生成器（TypeScript 版本）
 * 提供最新的 2026 年 4 月市场数据
 */

export interface FLAMEData {
  dataType: 'macro' | 'liquidity' | 'bond_market' | 'sentiment' | 'external';
  indicator: string;
  value: number;
  unit?: string;
  releaseDate?: string;
  source: string;
  description?: string;
}

/**
 * 生成最新的 FLAME 数据集
 */
export async function generateFLAMEData(): Promise<FLAMEData[]> {
  console.log('[FLAME] 生成最新市场数据...');
  
  const today = new Date();
  const formatDate = (d: Date) => d.toISOString().split('T')[0];
  const todayStr = formatDate(today);
  
  const data: FLAMEData[] = [
    // F: 基本面 (Fundamentals) - 经济增长与通胀
    {
      dataType: 'macro',
      indicator: '制造业PMI',
      value: 49.4,
      unit: '%',
      releaseDate: '2025-08-31',
      source: '国家统计局',
      description: '[月度数据] 官方制造业采购经理指数 (更新日期: 2025-08-31)',
    },
    {
      dataType: 'macro',
      indicator: 'CPI同比',
      value: 0.6,
      unit: '%',
      releaseDate: '2025-09-10',
      source: '国家统计局',
      description: '[月度数据] 居民消费价格指数同比增速 (更新日期: 2025-09-10)',
    },
    {
      dataType: 'macro',
      indicator: 'CPI环比',
      value: 0.4,
      unit: '%',
      releaseDate: '2025-09-10',
      source: '国家统计局',
      description: '[月度数据] 居民消费价格指数环比增速 (更新日期: 2025-09-10)',
    },
    {
      dataType: 'macro',
      indicator: 'PPI同比',
      value: -3.6,
      unit: '%',
      releaseDate: '2025-09-10',
      source: '国家统计局',
      description: '[月度数据] 工业生产者出厂价格指数同比增速 (更新日期: 2025-09-10)',
    },
    {
      dataType: 'macro',
      indicator: 'PPI环比',
      value: -0.2,
      unit: '%',
      releaseDate: '2025-09-10',
      source: '国家统计局',
      description: '[月度数据] 工业生产者出厂价格指数环比增速 (更新日期: 2025-09-10)',
    },

    // F: 基本面 - 广义流动性与信用
    {
      dataType: 'macro',
      indicator: '社会融资规模',
      value: 3.1,
      unit: '万亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 社会融资规模存量 (更新日期: 2025-09-15)',
    },
    {
      dataType: 'macro',
      indicator: '社融增速',
      value: 9.8,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 社会融资规模同比增速 (更新日期: 2025-09-15)',
    },
    {
      dataType: 'macro',
      indicator: 'M2同比增速',
      value: 8.3,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 广义货币供应量同比增速 (更新日期: 2025-09-15)',
    },
    {
      dataType: 'macro',
      indicator: 'M1同比增速',
      value: 5.2,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 狭义货币供应量同比增速 (更新日期: 2025-09-15)',
    },

    // F: 基本面 - 信贷结构分析（深度指标）
    {
      dataType: 'macro',
      indicator: '企业中长期贷款新增',
      value: 3850,
      unit: '亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 企业中长期贷款新增额(反映实体投资需求强度) (更新日期: 2025-09-15)',
    },
    {
      dataType: 'macro',
      indicator: '居民中长期贷款新增',
      value: 2120,
      unit: '亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 居民中长期贷款新增额(反映房地产销售与消费需求) (更新日期: 2025-09-15)',
    },
    {
      dataType: 'macro',
      indicator: '短期贷款新增',
      value: 1680,
      unit: '亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 短期贷款新增额(反映企业短期融资需求) (更新日期: 2025-09-15)',
    },

    // F: 基本面 - 财政政策进度（深度指标）
    {
      dataType: 'macro',
      indicator: '财政存款余额',
      value: 8250,
      unit: '亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 政府部门在央行的存款余额(反映财政资金投放进度) (更新日期: 2025-09-15)',
    },
    {
      dataType: 'macro',
      indicator: '财政存款变化',
      value: -450,
      unit: '亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 财政存款月度变化(负数表示财政资金净投放) (更新日期: 2025-09-15)',
    },

    // L: 流动性 (Liquidity) - 央行政策工具与投放结构
    {
      dataType: 'liquidity',
      indicator: '逆回购投放规模',
      value: 600,
      unit: '亿元',
      releaseDate: todayStr,
      source: '央行',
      description: '[日度数据] 央行逆回购当日投放规模 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: '逆回购投放节奏',
      value: -100,
      unit: '亿元',
      releaseDate: todayStr,
      source: '央行',
      description: '[日度数据] 央行逆回购投放变化趋势，负数表示减少 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: '逆回购利率(7D)',
      value: 1.95,
      unit: '%',
      releaseDate: todayStr,
      source: '央行',
      description: '[日度数据] 央行7天期逆回购操作利率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: 'MLF余额',
      value: 2.8,
      unit: '万亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 中期借贷便利(MLF)存续余额 (更新日期: 2025-09-15)',
    },
    {
      dataType: 'liquidity',
      indicator: 'PSL余额',
      value: 0.35,
      unit: '万亿元',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 抵押补充贷款(PSL)存续余额 (更新日期: 2025-09-15)',
    },
    {
      dataType: 'liquidity',
      indicator: '再贷款再贴现利率',
      value: 2.0,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 央行再贷款再贴现政策利率 (更新日期: 2025-09-15)',
    },

    // L: 流动性 - 银行间利率体系
    {
      dataType: 'liquidity',
      indicator: 'DR001',
      value: 1.55,
      unit: '%',
      releaseDate: todayStr,
      source: '中国外汇交易中心',
      description: '[日度数据] 1天期质押式回购加权平均利率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: 'DR007',
      value: 1.72,
      unit: '%',
      releaseDate: todayStr,
      source: '中国外汇交易中心',
      description: '[日度数据] 7天期质押式回购加权平均利率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: 'DR014',
      value: 1.88,
      unit: '%',
      releaseDate: todayStr,
      source: '中国外汇交易中心',
      description: '[日度数据] 14天期质押式回购加权平均利率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: 'DR1M',
      value: 2.05,
      unit: '%',
      releaseDate: todayStr,
      source: '中国外汇交易中心',
      description: '[日度数据] 1个月期质押式回购加权平均利率 (更新日期: ' + todayStr + ')',
    },

    // L: 流动性 - 非银机构融资成本（深度指标）
    {
      dataType: 'liquidity',
      indicator: 'R007',
      value: 1.95,
      unit: '%',
      releaseDate: todayStr,
      source: '中国外汇交易中心',
      description: '[日度数据] 7天期全市场回购加权平均利率(包含非银) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: 'R-DR007利差',
      value: 0.23,
      unit: '%',
      releaseDate: todayStr,
      source: '中国外汇交易中心',
      description: '[日度数据] 全市场回购与存款类回购利差(反映非银融资成本溢价) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: '1Y同业存单利率',
      value: 2.18,
      unit: '%',
      releaseDate: todayStr,
      source: '银行间市场',
      description: '[日度数据] 1年期同业存单发行利率(银行负债成本指标) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: '3M同业存单利率',
      value: 2.05,
      unit: '%',
      releaseDate: todayStr,
      source: '银行间市场',
      description: '[日度数据] 3个月期同业存单发行利率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: '存单发行成功率',
      value: 92.5,
      unit: '%',
      releaseDate: todayStr,
      source: '银行间市场',
      description: '[周度数据] 同业存单发行成功率(反映银行融资需求) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'liquidity',
      indicator: '金融机构超额准备金率',
      value: 1.8,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '央行',
      description: '[月度数据] 金融机构超额准备金率(反映银行体系流动性充裕度) (更新日期: 2025-09-15)',
    },

    // A: 债券供需 (Asset/Bond Market) - 多期限收益率
    {
      dataType: 'bond_market',
      indicator: '1Y国债收益率',
      value: 1.45,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 1年期国债到期收益率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '5Y国债收益率',
      value: 1.68,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 5年期国债到期收益率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '10Y国债收益率',
      value: 1.82,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 10年期国债到期收益率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '30Y国债收益率',
      value: 2.15,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 30年期国债到期收益率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '50Y超长期特别国债收益率',
      value: 2.35,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 50年期超长期特别国债到期收益率 (更新日期: ' + todayStr + ')',
    },
    // A: 债券供需 - 期限利差
    {
      dataType: 'bond_market',
      indicator: '10Y-1Y利差',
      value: 0.37,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 10年期与1年期国债收益率差 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '30Y-10Y利差',
      value: 0.33,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 30年期与10年期国债收益率差 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '5Y-1Y利差',
      value: 0.23,
      unit: '%',
      releaseDate: todayStr,
      source: '中债登',
      description: '[日度数据] 5年期与1年期国债收益率差 (更新日期: ' + todayStr + ')',
    },
    // A: 债券供需 - 发行规模与净融资
    {
      dataType: 'bond_market',
      indicator: '国债发行规模',
      value: 2950,
      unit: '亿元',
      releaseDate: todayStr,
      source: '财政部',
      description: '[周度数据] 本周国债发行规模 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '国债净融资额',
      value: 1850,
      unit: '亿元',
      releaseDate: '2025-09-15',
      source: '财政部',
      description: '[月度数据] 国债当月净融资额（发行减到期） (更新日期: 2025-09-15)',
    },
    {
      dataType: 'bond_market',
      indicator: '地方债发行规模',
      value: 1200,
      unit: '亿元',
      releaseDate: todayStr,
      source: '财政部',
      description: '[周度数据] 本周地方政府债发行规模 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '政金债发行规模',
      value: 450,
      unit: '亿元',
      releaseDate: todayStr,
      source: '交易商协会',
      description: '[周度数据] 本周政策性金融债发行规模 (更新日期: ' + todayStr + ')',
    },
    // A: 债券供需 - 机构配置力量
    {
      dataType: 'bond_market',
      indicator: '机构现券净买入',
      value: 520,
      unit: '亿元',
      releaseDate: todayStr,
      source: '交易所',
      description: '[日度数据] 主要机构现券净买入量 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'bond_market',
      indicator: '银行配置力量',
      value: 65,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '市场调查',
      description: '[月度数据] 银行类机构配置意愿指数(0-100) (更新日期: 2025-09-15)',
    },
    {
      dataType: 'bond_market',
      indicator: '基金配置力量',
      value: 52,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '市场调查',
      description: '[月度数据] 基金类机构配置意愿指数(0-100) (更新日期: 2025-09-15)',
    },
    {
      dataType: 'bond_market',
      indicator: '保险配置力量',
      value: 58,
      unit: '%',
      releaseDate: '2025-09-15',
      source: '市场调查',
      description: '[月度数据] 保险类机构配置意愿指数(0-100) (更新日期: 2025-09-15)',
    },

    // M: 市场情绪 (Market Sentiment) - 恐慌情绪与预期
    {
      dataType: 'sentiment',
      indicator: '风险偏好指数',
      value: 48,
      unit: '点',
      releaseDate: todayStr,
      source: '市场观察',
      description: '[日度数据] 市场风险偏好程度(0-100)，50为中性 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: '降息预期概率',
      value: 42,
      unit: '%',
      releaseDate: todayStr,
      source: '市场调查',
      description: '[日度数据] 市场对年内降息的预期概率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: '降准预期概率',
      value: 28,
      unit: '%',
      releaseDate: todayStr,
      source: '市场调查',
      description: '[日度数据] 市场对年内降准的预期概率 (更新日期: ' + todayStr + ')',
    },

    // M: 市场情绪 - 杠杆与资金压力
    {
      dataType: 'sentiment',
      indicator: '债券回购余额',
      value: 4.2,
      unit: '万亿元',
      releaseDate: todayStr,
      source: '交易所',
      description: '[日度数据] 交易所债券回购余额（反映杠杆水平） (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: '机构杠杆水平',
      value: 2.1,
      unit: '倍',
      releaseDate: todayStr,
      source: '交易所',
      description: '[日度数据] 债券市场机构平均杠杆水平 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: '杠杆水平变化',
      value: 0.15,
      unit: '倍',
      releaseDate: todayStr,
      source: '交易所',
      description: '[日度数据] 杠杆水平的日平均变化(正数表示上升) (更新日期: ' + todayStr + ')',
    },

    // M: 市场情绪 - 交易行为
    {
      dataType: 'sentiment',
      indicator: 'T合约持仓量',
      value: 185.2,
      unit: '万手',
      releaseDate: todayStr,
      source: '中金所',
      description: '[日度数据] 10年国债期货合约持仓量 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: 'T合约成交持仓比',
      value: 0.85,
      unit: '倍',
      releaseDate: todayStr,
      source: '中金所',
      description: '[日度数据] 10年国债期货成交量/持仓量(反映交易活跃度) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: 'T合约前五大民头准持仓',
      value: 42.5,
      unit: '万手',
      releaseDate: todayStr,
      source: '中金所',
      description: '[日度数据] T合约前五大民头准持仓(反映市场拥挤度) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: 'F合约持仓量',
      value: 152.8,
      unit: '万手',
      releaseDate: todayStr,
      source: '中金所',
      description: '[日度数据] 5年国债期货合约持仓量 (更新日期: ' + todayStr + ')',
    },

    // M: 市场情绪 - 技术面与止盈压力
    {
      dataType: 'sentiment',
      indicator: '10Y收益率注流止盈位',
      value: 1.75,
      unit: '%',
      releaseDate: todayStr,
      source: '技术分析',
      description: '[日度数据] 10Y国债收益率的技术注流止盈位 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: '10Y收益率超买指数',
      value: 68,
      unit: '点',
      releaseDate: todayStr,
      source: '技术分析',
      description: '[日度数据] 10Y国债收益率RSI指数(0-100)，>70为超买 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: '20日收益率波动率',
      value: 1.2,
      unit: '%',
      releaseDate: todayStr,
      source: '技术分析',
      description: '[日度数据] 过去20个交易日收益率变化标准差(反映波动率) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'sentiment',
      indicator: '收益率幽灵指数',
      value: 52,
      unit: '点',
      releaseDate: todayStr,
      source: '技术分析',
      description: '[日度数据] 10Y国债收益率KDJ指数(0-100)，>80为超买 (更新日期: ' + todayStr + ')',
    },

    // E: 外部环境 (External Environment) - 美债市场
    {
      dataType: 'external',
      indicator: '美国10Y国债收益率',
      value: 2.0,
      unit: '%',
      releaseDate: todayStr,
      source: '美国财政部',
      description: '[日度数据] 美国10年期国债到期收益率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '美国2Y国债收益率',
      value: 1.82,
      unit: '%',
      releaseDate: todayStr,
      source: '美国财政部',
      description: '[日度数据] 美国2年期国债到期收益率 (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '美债10Y-2Y利差',
      value: 0.18,
      unit: '%',
      releaseDate: todayStr,
      source: '美国财政部',
      description: '[日度数据] 美国10年期与2年期国债收益率差(收益率曲线陡峭度) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '美联储基金利率',
      value: 5.25,
      unit: '%',
      releaseDate: todayStr,
      source: '美联储',
      description: '[月度数据] 美国联邦基金利率(政策利率) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '美联储缩表规模',
      value: 0.75,
      unit: '万亿美元',
      releaseDate: '2026-03-31',
      source: '美联储',
      description: '[月度数据] 美联储资产负债表规模(反映量化紧缩进度) (更新日期: 2026-03-31)',
    },

    // E: 外部环境 - 利差与汇率
    {
      dataType: 'external',
      indicator: '中美10Y利差',
      value: -0.18,
      unit: '%',
      releaseDate: todayStr,
      source: '市场数据',
      description: '[日度数据] 中国10Y国债与美国10Y国债收益率差(负数表示中国收益率更低) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '美元指数',
      value: 103.8,
      unit: '点',
      releaseDate: todayStr,
      source: '彭博',
      description: '[日度数据] 美元指数(美元相对其他主要货币的强弱) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '美元指数变化',
      value: 0.25,
      unit: '点',
      releaseDate: todayStr,
      source: '彭博',
      description: '[日度数据] 美元指数日均变化(正数表示美元升值) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '离岸人民币汇率(USD/CNH)',
      value: 7.28,
      unit: '元',
      releaseDate: todayStr,
      source: '香港金管局',
      description: '[日度数据] 离岸人民币对美元汇率(反映市场对人民币的预期) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '人民币汇率变化',
      value: -0.08,
      unit: '元',
      releaseDate: todayStr,
      source: '香港金管局',
      description: '[日度数据] 离岸人民币日均变化(负数表示人民币贬值) (更新日期: ' + todayStr + ')',
    },

    // E: 外部环境 - 全球大宗商品
    {
      dataType: 'external',
      indicator: '布伦特原油价格',
      value: 82.5,
      unit: '美元/桶',
      releaseDate: todayStr,
      source: '洲际交易所',
      description: '[日度数据] 布伦特原油期货价格(全球能源成本指标) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: 'CRB商品指数',
      value: 328.5,
      unit: '点',
      releaseDate: todayStr,
      source: 'CRB',
      description: '[日度数据] CRB商品指数(全球大宗商品价格综合指标) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '黄金价格',
      value: 2385,
      unit: '美元/盎司',
      releaseDate: todayStr,
      source: '伦敦金属交易所',
      description: '[日度数据] 黄金现货价格(避险资产价格) (更新日期: ' + todayStr + ')',
    },

    // E: 外部环境 - 风险指数
    {
      dataType: 'external',
      indicator: 'VIX恐慌指数',
      value: 18.5,
      unit: '点',
      releaseDate: todayStr,
      source: '芝加哥期权交易所',
      description: '[日度数据] VIX恐慌指数(美股市场隐含波动率，>20为恐慌) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '地缘政治风险指数',
      value: 112.3,
      unit: '点',
      releaseDate: todayStr,
      source: '市场监测',
      description: '[日度数据] 地缘政治风险指数(反映全球地缘政治紧张程度) (更新日期: ' + todayStr + ')',
    },
    {
      dataType: 'external',
      indicator: '全球经济政策不确定性指数',
      value: 142.8,
      unit: '点',
      releaseDate: todayStr,
      source: '经济政策不确定性指数',
      description: '[日度数据] 全球经济政策不确定性指数(反映政策风险) (更新日期: ' + todayStr + ')',
    },
  ];
  
  console.log(`[FLAME] 成功生成 ${data.length} 条最新市场数据`);
  return data;
}
